apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello-deployment
 namespace: helloworld
 labels:
  app: hello
spec:
 replicas: 3
 selector:
  matchLabels:
   app: hello
 template:
  metadata:
   labels:
    app: hello
  spec:
   containers:
    - name: hello
      image: sekenberg/examinationsuppgift:latest
      imagePullPolicy: IfNotPresent